# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-remote-theme

remote_theme: daviddarnes/alembic@main

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
social: # jekyll-seo-tag > social overrides
  name: Matt Durlin # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/daviddarnes
    - https://github.com/mdurlin
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Matt Durlin - Nashville Rock Music Reviews # Needed for Siteleaf
    output: true
    description: "Christian rock, punk rock, Nashville rock concerts, band interviews" # The post list page content
    feature_text: |
      Welcome to Nashville's best rock music blog. Here you'll find reviews of the latest Christian rock, punk rock, and other rock music. We also cover Nashville rock concerts and interview bands.
    feature_image: "https://images.pexels.com/photos/13899090/pexels-photo-13899090.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Matt Durlin" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.png" # Site logo, also used in jekyll-seo-tag
description: "Matt Durlin - Rock Music Reviews, Interviews and More" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.mattdurlin.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/mdurlin/md-web-com"
email: "mattdurlin@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo.png'
  32: '/assets/logos/logo.png'
  96: '/assets/logos/logo.png'
  120: '/assets/logos/logo.png'
  144: '/assets/logos/logo.png'
  180: '/assets/logos/logo.png'
  512: '/assets/logos/logo.png'
  1024: '/assets/logos/logo.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Reviews
  url: /reviews/
- title: Artist Spotlight
  url: /spotlight/
- title: Nashville Events
  url: /events/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Instagram: https://www.instagram.com/mattd_rock_com

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
